datasource:
  default: ${APP_ENV}
  development:
    username: sa
    password: sa
    url: "jdbc:h2:./database"
  production:
    username: "postgres"
    password: "YhefhCtow5v5LyC0Mdvg"
    url: "jdbc:postgresql://postgres:YhefhCtow5v5LyC0Mdvg@containers-us-west-87.railway.app:6949/railway"

ebean:
  migration:
    run: true
